### PR TITLE
[flink] Avoid FileNotFoundException in snapshot loop

### LINKED ISSUE #1302: [Feature] Avoid FileNotFoundException in snapshot loop
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

In `GlobalFullCompactionSinkWrite.checkSuccessfulFullCompaction`, we have a loop to look at all snapshots.
But if there is committer to expire snapshots, there may be `FileNotFoundException`.

We can avoid this exception, if not found a snapshot file, check earliest snapshot in the loop.

### Solution

_No response_

### Anything else?

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by JingsongLi**
### Purpose

Linked issue: close #1302

After modifying this to safely loop, we can remove limitation in documentation, users can set a free full compaction commits delta.

### Tests

`SnapshotManagerTest.testTraversalSnapshotsFromLatestSafely`.

### CODE REVIEW

File: paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java [hunk 1]
```diff
@@ -222,6 +223,46 @@ public Optional<Snapshot> latestSnapshotOfUser(String user) {
         return Optional.empty();
     }
 
+    /**
+     * Traversal snapshots from latest to earliest safely, this is applied on the writer side
+     * because the committer may delete obsolete snapshots, which may cause the writer to encounter
+     * unreadable snapshots.
+     */
+    public void traversalSnapshotsFromLatestSafely(Function<Snapshot, Boolean> consumer) {
```
Comment (yuzelin) [inline paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java:231]: How about using `java.util.function.Predicate` ?

Comment (JingsongLi) [reply paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java:231]: It should not be a predicate, it is a consumer, and just return a early break boolean.

Comment (yuzelin) [reply paimon-core/src/main/java/org/apache/paimon/utils/SnapshotManager.java:231]: Ok, make sense.

**Review by yuzelin — APPROVED** [review]
LGTM
