### PR TITLE
[flink] Flink CDC actions support using Hive catalog and ignore case by default

### LINKED ISSUE #890: [Bug] MySqlSyncTableAction should support case ignore mode
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

0.4

### Compute Engine

flink

### Minimal reproduce step

Fields with upperCase sync to HiveCatalog.
There is an exception, see https://github.com/apache/incubator-paimon/pull/413

### What doesn't meet your expectations?

Provide a mode to convert upperCase to lowerCase automatic.

### Anything else?

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by yuzelin**
### Purpose

Fix #890 

Support specifying hive metastore in cdc actions. In this case, the action will ignore case for database, table and column name by default because Hive does so.

### Tests

`MySqlIgnoreCaseE2EeTest#testSyncDatabase`

### API and Format 

`Catalog#caseSensitive`
Action's `paimon-conf` is replaced by `catalog-conf` and `table-conf`

### Documentation

CDC Ingestion

### CODE REVIEW

File: paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/CdcParsingProcessFunctionBase.java [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+ * limitations under the License.
+ */
+
+package org.apache.paimon.flink.sink.cdc;
+
+import org.apache.flink.configuration.Configuration;
+import org.apache.flink.streaming.api.functions.ProcessFunction;
+
+/** Base class of {@link ProcessFunction} for CDC parsing. */
+public abstract class CdcParsingProcessFunctionBase<T, O> extends ProcessFunction<T, O> {
```
Comment (JingsongLi) [inline paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/CdcParsingProcessFunctionBase.java:25]: No need to create an abstract class...

File: paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableAction.java [hunk 2]
```diff
@@ -124,7 +124,15 @@ public void build(StreamExecutionEnvironment env) throws Exception {
         Catalog catalog =
                 CatalogFactory.createCatalog(
                         CatalogContext.create(
-                                new Options().set(CatalogOptions.WAREHOUSE, warehouse)));
+                                new Options(paimonConfig)
+                                        .set(CatalogOptions.WAREHOUSE, warehouse)));
+        MySqlActionUtils.removeTableDefaultOptions(paimonConfig);
```
Comment (JingsongLi) [inline paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableAction.java:129]: Maybe we can create a table options and a catalog options.

File: paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableAction.java [hunk 3]
```diff
@@ -154,14 +162,23 @@ public void build(StreamExecutionEnvironment env) throws Exception {
...
+                        .withCaseSensitive(catalog.caseSensitive());
         String sinkParallelism = paimonConfig.get(FlinkConnectorOptions.SINK_PARALLELISM.key());
         if (sinkParallelism != null) {
             sinkBuilder.withParallelism(Integer.parseInt(sinkParallelism));
         }
         sinkBuilder.build();
     }
 
+    private void toCaseInsensitiveForm() {
+        database = database.toLowerCase();
```
Comment (JingsongLi) [inline paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSyncTableAction.java:175]: Only validate here is OK

File: paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/CdcRecord.java [hunk 4]
```diff
@@ -131,6 +132,20 @@ public Optional<GenericRow> toGenericRow(List<DataField> dataFields) {
         return Optional.of(genericRow);
     }
 
+    public CdcRecord toCaseInsensitiveForm() {
```
Comment (JingsongLi) [inline paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/CdcRecord.java:135]: It is better to just lower case in creation.

File: paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSchema.java [hunk 5]
```diff
@@ -31,8 +31,8 @@
 /** Utility class to load MySQL table schema with JDBC. */
 public class MySqlSchema {
 
-    private final String databaseName;
-    private final String tableName;
+    private String databaseName;
+    private String tableName;
 
     private final Map<String, DataType> fields;
```
Comment (JingsongLi) [inline paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/action/cdc/mysql/MySqlSchema.java:37]: It should be a `LinkedHashMap`

File: paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/CdcMultiTableParsingProcessFunction.java [hunk 6]
```diff
@@ -42,18 +42,22 @@
...
 
     private transient EventParser<T> parser;
     private transient Map<String, OutputTag<List<DataField>>> updatedDataFieldsOutputTags;
     private transient Map<String, OutputTag<CdcRecord>> recordOutputTags;
 
-    public CdcMultiTableParsingProcessFunction(EventParser.Factory<T> parserFactory) {
+    public CdcMultiTableParsingProcessFunction(
+            EventParser.Factory<T> parserFactory, boolean caseSensitive) {
         this.parserFactory = parserFactory;
+        this.caseSensitive = caseSensitive;
```
Comment (JingsongLi) [inline paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/sink/cdc/CdcMultiTableParsingProcessFunction.java:54]: It is OK to just let `EventParser.Factory` know the `caseSensitive` in actions.
We don't need to modify `CdcMultiTableParsingProcessFunction`.

**Review by JingsongLi — APPROVED** [review]
+1
