### PR TITLE
[Bug] Fix the IndexOutOfBoundsException when  lookup empty sortedRun

### LINKED ISSUE #2528: [Bug] LookupUtils may throw IndexOutOfBoundsException when SortedRun is empty
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

0.6.0

### Compute Engine

Flink

### Minimal reproduce step

image

### What doesn't meet your expectations?

IndexOutOfBoundsException

### Anything else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by Aitozi**
### Purpose

Linked issue: close #2528

### CODE REVIEW

File: paimon-core/src/main/java/org/apache/paimon/mergetree/LookupUtils.java [hunk 1]
```diff
@@ -59,6 +59,9 @@ public static <T> T lookup(
             SortedRun level,
             BiFunctionWithIOE<InternalRow, DataFileMeta, T> lookup)
             throws IOException {
+        if (!level.nonEmpty()) {
```
Comment (JingsongLi) [inline paimon-core/src/main/java/org/apache/paimon/mergetree/LookupUtils.java:62]: Can you add a test for this method?

Comment (Aitozi) [reply paimon-core/src/main/java/org/apache/paimon/mergetree/LookupUtils.java:62]: done

**Review by JingsongLi — APPROVED** [review]
+1
