### PR TITLE
[Bug] Fix the parquet.compression do no work in parquet format

### LINKED ISSUE #1494: [Bug] file.compression do no work for parquet format
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

master

### Compute Engine

parquet format

### Minimal reproduce step

image

In parquet format, it will use `compress` key to extract from the option, and it has the higher preference than from the `file.compression`. So the actual work key is `compress`

### What doesn't meet your expectations?

the actual compression algorithm

### Anything else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by Aitozi**
### Purpose

Linked issue: close #1494

### CODE REVIEW

File: paimon-format/src/main/java/org/apache/paimon/format/parquet/writer/RowDataParquetBuilder.java [hunk 1]
```diff
@@ -45,15 +47,8 @@ public RowDataParquetBuilder(RowType rowType, Options conf) {
...
             throws IOException {
 
-        String compressName = CompressionCodecName.SNAPPY.name();
-        if (null != compression) {
-            compressName = compression;
-        }
-
         return new ParquetRowDataBuilder(out, rowType)
-                .withCompressionCodec(
-                        CompressionCodecName.fromConf(
```
Comment (Aitozi) [inline paimon-format/src/main/java/org/apache/paimon/format/parquet/writer/RowDataParquetBuilder.java:55]: In `org.apache.paimon.format.parquet.ParquetFileFormatFactory#supplyDefaultOptions` it will always set the `parquet.compression` to snappy. So the effective compression option is always snappy.
