### PR TITLE
[flink] Fix the problem that flink job for reading paimon won't recov…

### LINKED ISSUE #2761: [Bug] Flink can't recover from exception as 'OutOfRangeException' when sometime the paimon snapshot is expired
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

0.6

### Compute Engine

flink

### Minimal reproduce step

1. Flink job for reading paimon is running for a while and left some checkpoints
2. Flink job try to failover for some exception，and the snapshot of paimon to read is expired.
3. Flink job can't reading latest data on paimon，bu only log "Failed to enumerate files，org.apache.paimon.table.source OutOfRangeException.... ", won't try to cancel job an restart。

like this:
image

### What doesn't meet your expectations?

When catch `OutOfRangeException`，flink job should try to failover。

### Anything else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by bridgeDream**
…er when catching snapshot OutOfRangeException

### Purpose

Linked issue: close #2761

Throw a runtime exception in flink job to try to failover, when reading paimon found a OutOfRangeException

### Tests

None

### API and Format

None
### Documentation

None

### CODE REVIEW

File: paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/ContinuousFileSplitEnumerator.java [hunk 1]
```diff
@@ -210,6 +211,8 @@ protected void processDiscoveredSplits(
                 LOG.debug("Catching EndOfStreamException, the stream is finished.");
                 finished = true;
                 assignSplits();
+            } else if (error instanceof OutOfRangeException) {
+                throw (RuntimeException) error;
             } else {
                 LOG.error("Failed to enumerate files", error);
```
Comment (JingsongLi) [inline paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/ContinuousFileSplitEnumerator.java:217]: Maybe we need to throw all exceptions here?

Comment (bridgeDream) [reply paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/ContinuousFileSplitEnumerator.java:214]: I agree with that. Thank you

File: paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/ContinuousFileSplitEnumerator.java [hunk 2]
```diff
@@ -212,6 +212,7 @@ protected void processDiscoveredSplits(
                 assignSplits();
             } else {
                 LOG.error("Failed to enumerate files", error);
+                throw (RuntimeException) error;
```
Comment (JingsongLi) [inline paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/ContinuousFileSplitEnumerator.java:215]: throw new RuntimeException(error)?

Comment (bridgeDream) [reply paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/source/ContinuousFileSplitEnumerator.java]: > throw new RuntimeException(error)?

Done, FYI !

**Comment by JingsongLi** [comment]
+1
