### PR TITLE
[hive] Hive read paimon table should always build schema from existing Paimon table schema first

### LINKED ISSUE #1198: [Bug] Hive cannot query the timestamp field of the paimon table
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

paimon-hive-connector-3.1-0.5-20230519.001932-15.jar

### Compute Engine

hive-3.1.0

### Minimal reproduce step

0: jdbc:hive2://ambari.bi.lyf.test:2181,nn01.> select id,order_no,create_time from ods.zt_tc_order_paimon a;
INFO  : Compiling command(queryId=hive_20230522165519_4501567f-83d4-40ae-b6a1-5cc8c2f1a6f9): select id,order_no,create_time from ods.zt_tc_order_paimon a
INFO  : Semantic Analysis Completed (retrial = false)
INFO  : Returning Hive schema: Schema(fieldSchemas:[FieldSchema(name:id, type:bigint, comment:null), FieldSchema(name:order_no, type:string, comment:null), FieldSchema(name:create_time, type:timestamp, comment:null)], properties:null)
INFO  : Completed compiling command(queryId=hive_20230522165519_4501567f-83d4-40ae-b6a1-5cc8c2f1a6f9); Time taken: 0.325 seconds
INFO  : Executing command(queryId=hive_20230522165519_4501567f-83d4-40ae-b6a1-5cc8c2f1a6f9): select id,order_no,create_time from ods.zt_tc_order_paimon a
INFO  : Completed executing command(queryId=hive_20230522165519_4501567f-83d4-40ae-b6a1-5cc8c2f1a6f9); Time taken: 0.25 seconds
INFO  : OK
java.lang.IllegalArgumentException: Timestamp format must be yyyy-mm-dd hh:mm:ss[.fffffffff]
	at java.sql.Timestamp.valueOf(Timestamp.java:237)
	at org.apache.hive.jdbc.HiveBaseResultSet.evaluate(HiveBaseResultSet.java:445)
	at org.apache.hive.jdbc.HiveBaseResultSet.getColumnValue(HiveBaseResultSet.java:425)
	at org.apache.hive.jdbc.HiveBaseResultSet.getObject(HiveBaseResultSet.java:467)
	at org.apache.hive.beeline.Rows$Row.<init>(Rows.java:160)
	at org.apache.hive.beeline.BufferedRows.<init>(BufferedRows.java:57)
	at org.apache.hive.beeline.IncrementalRowsWithNormalization.<init>(IncrementalRowsWithNormalization.java:50)
	at org.apache.hive.beeline.BeeLine.print(BeeLine.java:2305)
	at org.apache.hive.beeline.Commands.executeInternal(Commands.java:1026)
	at org.apache.hive.beeline.Commands.execute(Commands.java:1201)
	at org.apache.hive.beeline.Commands.sql(Commands.java:1130)
	at org.apache.hive.beeline.BeeLine.dispatch(BeeLine.java:1480)
	at org.apache.hive.beeline.BeeLine.execute(BeeLine.java:1342)
	at org.apache.hive.beeline.BeeLine.begin(BeeLine.java:1126)
	at org.apache.hive.beeline.BeeLine.mainWithInputRedirection(BeeLine.java:546)
	at org.apache.hive.beeline.BeeLine.main(BeeLine.java:528)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:318)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:232)
Error: Unrecognized column type:TIMESTAMP_TYPE (state=,code=0)
0: jdbc:hive2://ambari.bi.lyf.test:2181,nn01.>

### What doesn't meet your expectations?

timestamp format error

### Anything else?

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by yuzelin**
### Purpose

When reading from Hive, the  current `HiveSchema` maybe constructed from Hive schema infomation even Paimon schema is available. This PR fix it.

This PR can fix #1198 because now the `TIMESTAMP` precision can be set correctly.

### Tests

`PaimonStorageHandlerITCase#testDateAndTimestamp`

### API and Format

no
### Documentation

no

### CODE REVIEW

File: paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/HiveSchema.java [hunk 1]
```diff
@@ -112,21 +111,24 @@ public static HiveSchema extract(@Nullable Configuration configuration, Properti
...
+        // matches and still build from Paimon table schema
+        if (tableSchema.isPresent()) {
+            if (columnNames.size() > 0 && typeInfos.size() > 0) {
+                LOG.debug(
+                        "Extract schema with exists DDL and exists paimon table, table location:[{}].",
+                        location);
+                checkSchemaMatched(columnNames, typeInfos, tableSchema.get());
+            }
+
+            return new HiveSchema(new RowType(tableSchema.get().fields()));
```
Comment (JingsongLi) [inline paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/HiveSchema.java:125]: Don't do this.

For example, Hive DDL can be f1, f2, but table can be f0,f1,f2,f3,f4

Comment (yuzelin) [reply paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/HiveSchema.java]: modified.

File: paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/HiveSchema.java [hunk 2]
```diff
@@ -121,16 +125,20 @@ public static HiveSchema extract(@Nullable Configuration configuration, Properti
                     "Extract schema with exists DDL and exists paimon table, table location:[{}].",
                     location);
             checkSchemaMatched(columnNames, typeInfos, tableSchema.get());
-            // Use paimon table column comment when the paimon table exists.
-            comments =
+            // Use paimon table data types and column comments when the paimon table exists.
```
Comment (JingsongLi) [inline paimon-hive/paimon-hive-connector-common/src/main/java/org/apache/paimon/hive/HiveSchema.java:128]: why? add comment?

**Review by JingsongLi — APPROVED** [review]
+1
